# Generated by Django 4.0.3 on 2022-03-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название курса')),
                ('length_of_time', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
            ],
        ),
    ]
