# Generated by Django 4.0.3 on 2022-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название курса')),
                ('length_of_time', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('status', models.CharField(max_length=128, verbose_name='Статус')),
                ('mark', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('action_object', models.CharField(max_length=128, verbose_name='Действие над объектом')),
            ],
        ),
        migrations.DeleteModel(
            name='MyCourses',
        ),
    ]
