# Generated by Django 4.0.3 on 2022-03-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_mycourse_delete_mycourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
            ],
        ),
    ]
