# Generated by Django 4.0.3 on 2022-03-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_educator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userside.educator'),
        ),
    ]
