# Generated by Django 4.0.3 on 2022-03-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourse',
            options={'ordering': ['length_of_time'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
