# Generated by Django 4.0.3 on 2022-03-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_alter_mycourse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycourses', to='userside.educator'),
        ),
    ]
