# Generated by Django 4.0.3 on 2022-03-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_mycourse_date_begin_mycourse_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название курса')),
                ('length_of_time', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('status', models.CharField(max_length=128, verbose_name='Статус')),
                ('mark', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('action_object', models.CharField(max_length=128, verbose_name='Действие над объектом')),
                ('date_begin', models.DateField(verbose_name='Дата начала обучения')),
                ('date_end', models.DateField(verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['length_of_time'],
            },
        ),
        migrations.CreateModel(
            name='My_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='educator',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Препод'),
        ),
        migrations.DeleteModel(
            name='mycourse',
        ),
        migrations.AddField(
            model_name='course',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycourses', to='userside.educator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.ManyToManyField(to='userside.course'),
        ),
    ]
