# Generated by Django 4.0.3 on 2022-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_course_my_documents_notification_alter_educator_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='educator',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Преподаватель'),
        ),
    ]
