# Generated by Django 4.0.3 on 2022-03-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0010_courseinstanse_remove_course_action_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courseInstanse',
            new_name='mycourse',
        ),
        migrations.DeleteModel(
            name='My_documents',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='course',
            name='length_of_month',
        ),
        migrations.AlterField(
            model_name='course',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='userside.educator'),
        ),
    ]
