# Generated by Django 4.0.3 on 2022-03-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0011_rename_courseinstanse_mycourse_delete_my_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='length_of_hous',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='length_of_week',
        ),
    ]
