# Generated by Django 4.0.3 on 2022-03-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0013_course_sb_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sb_number',
        ),
    ]
