---

- hosts: "all"
  become: true

  tasks:
    - name: "Install packages"
      apt:
        name: ['nginx','docker.io','python3-pip']
        state: "latest"
        update_cache: true

    - name: "Install pip packages"
      pip:
        name: ['docker-py']

    - name: "Pull docker image"
      shell: docker pull bairit/django_test_project:1.01

    - name: "Remove old container"
      docker_container:
        name: django-test-project
        image: bairit/django_test_project
        state: absent

    - name: "Create directories"
      file: path={{ item }} state=directory mode=0700
      with_items:
        - "/var/docker/django_test_project/conf"
        - "/var/docker/django_test_project/data"

    - name: Start container
      docker_container:
        name: django_test_project
        image: bairit/django_test_project:1.01
        restart_policy: always
        state: started
        ports:
          - 0.0.0.0:8000:8000
        volumes:
          - "/var/docker/django_test_project/conf:/conf"
          - "/var/docker/django_test_project/data:/data"


